#!/usr/bin/env python3
"""HTTP API for the trending-audio downloader — drop-in for content automation.

Endpoints
---------
POST /v1/download        {"url": "...", "niche": "...", "title": "...", "artist": "..."}
                          -> downloads the audio, saves to library/<niche>/, returns
                             {ok, path, title, artist, provider, sha256, bytes,
                              duration_s, cached, storage, ...}
                          ?cookies=... (JSON browser export OR a Netscape cookie
                          string) supplies a session for Instagram/private sources
POST /v1/song            {"title": "...", "artist": "...", "niche": "reels",
                          "instagram_url": "...", "cookies": [...]}
                          -> resolves a song NAME to audio: Instagram (URL, then
                             audio-page search) first, then SoundCloud/YouTube.
                             Use this with a row from /v1/trending to get the
                             actual trending track.
GET  /v1/library/<niche>  -> list of saved entries (manifest)
GET  /v1/file/<niche>/<name>  -> serve the downloaded audio file
GET  /health              -> liveness + library storage accounting

Run
---
.venv/bin/python server.py --port 8000 --library /path/library
Then POST from your automation system, e.g.:
  curl -X POST localhost:8000/v1/download \
       -H 'Content-Type: application/json' \
       -d '{"url":"https://www.instagram.com/reel/XXXX/","niche":"self-improvement"}'
"""
from __future__ import annotations

import argparse
import json
import os
import tempfile

from flask import Flask, jsonify, request, send_file, abort

from trend_scraper.audio import AudioLibrary

ROOT = os.path.dirname(os.path.abspath(__file__))
DEFAULT_LIBRARY = os.getenv("TL_LIBRARY", os.path.join(ROOT, "library"))
_MAX_CONCURRENT = int(os.getenv("TL_MAX_CONCURRENT", "2"))  # yt-dlp+ffmpeg is RAM-heavy

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 2 * 1024 * 1024  # request body cap (2MB, urls only)
app.config["LIBRARY"] = DEFAULT_LIBRARY             # set at import; gunicorn loads app directly

# Serialize heavy downloads so a burst of requests can't OOM a free-tier instance.
_download_slots = __import__("threading").BoundedSemaphore(max(1, _MAX_CONCURRENT))


def _write_cookies(cookies) -> str | None:
    """Persist session cookies to a Netscape cookie file for yt-dlp.

    Accepts either:
      * a Netscape-format string (used verbatim), or
      * a list/dict of cookie objects (browser-export shape:
        [{name, value, domain, path, secure, expirationDate}, ...]).

    yt-dlp's `cookiefile` ONLY understands Netscape format. Writing the JSON dict
    straight to disk (the previous behaviour) made every authenticated fetch fail
    to parse, which is why Instagram downloads could never succeed.
    """
    if not cookies:
        return None
    fd, path = tempfile.mkstemp(suffix=".txt")
    with os.fdopen(fd, "w") as fh:
        if isinstance(cookies, str):
            text = cookies.strip()
            if text.startswith("# Netscape") or "\t" in text:
                fh.write(text if text.endswith("\n") else text + "\n")
                return path
            try:                       # tolerate a JSON string body
                cookies = json.loads(text)
            except Exception:          # noqa: BLE001
                fh.write(text if text.endswith("\n") else text + "\n")
                return path

        # normalise to a list of cookie dicts
        if isinstance(cookies, dict):
            items = []
            for name, value in cookies.items():
                if isinstance(value, dict):
                    items.append({"name": name, **value})
                else:
                    items.append({"name": name, "value": value})
            cookies = items

        fh.write("# Netscape HTTP Cookie File\n")
        fh.write("# generated by trending-audio-api\n")
        for c in cookies or []:
            if not isinstance(c, dict):
                continue
            name = str(c.get("name") or "").strip()
            if not name:
                continue
            value = str(c.get("value") or "")
            domain = str(c.get("domain") or ".instagram.com").strip()
            cpath = str(c.get("path") or "/")
            secure = "TRUE" if c.get("secure") else "FALSE"
            expires = c.get("expirationDate") or c.get("expires") or 0
            try:
                expires = int(float(expires))
            except (TypeError, ValueError):
                expires = 0
            # domain-scope flag: TRUE when the cookie applies to subdomains
            scope = "TRUE" if domain.startswith(".") else "FALSE"
            fh.write("\t".join([domain, scope, cpath, secure,
                                str(expires), name, value]) + "\n")
    return path


@app.get("/")
def index():
    return jsonify({
        "service": "trending-audio-api",
        "status": "ok",
        "docs": "USAGE.md in the repo",
        "endpoints": {
            "health": "GET /health",
            "trending": "GET /v1/trending/<niche>?limit=20&refresh=0",
            "niches": "GET /v1/niches",
            "download": "POST /v1/download  {url, niche?, title?, artist?, cookies?}",
            "library": "GET /v1/library/<niche>",
            "file": "GET /v1/file/<niche>/<filename>",
        },
    })


@app.get("/favicon.ico")
def favicon():
    return ("", 204)


@app.get("/v1/trending/<niche>")
def trending(niche: str):
    """Return ranked trending audio for a niche (discovery, cached per day).

    Runs the browser-free discovery path so it is safe on the free-tier API:
    aggregator/evergreen feeds + Wayback, no headless browser. Results are
    ranked by the composite trend score (cross-source corroboration + momentum).
    """
    try:
        limit = max(1, min(int(request.args.get("limit", 20)), 100))
    except ValueError:
        limit = 20
    use_cache = request.args.get("refresh", "0") != "1"
    try:
        from trend_scraper import Niche, TrendingAudioEngine
        engine = TrendingAudioEngine(
            cache_dir=os.path.join(app.config["LIBRARY"], "_trending"),
            use_search=True,         # browser-free Bing/DDG-HTML search
            use_stealth=False,       # no chromium on the free-tier image
            deadline_s=float(os.getenv("TL_TRENDING_BUDGET_S", "90")),
        )
        tracks = engine.collect(Niche.from_name(niche), use_cache=use_cache)
        return jsonify({
            "niche": Niche.from_name(niche).name,
            "count": min(limit, len(tracks)),
            "cached": use_cache,
            "results": [t.__dict__ for t in tracks[:limit]],
        })
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)[:300]}), 500


@app.get("/v1/niches")
def niches():
    """List the niches the engine understands."""
    from trend_scraper.niches import all_niches
    return jsonify({"niches": all_niches()})


@app.get("/health")
def health():
    """Liveness + storage accounting.

    Reports the library footprint against its cap so the automation side can see
    storage pressure before a download fails on it.
    """
    lib = AudioLibrary(app.config["LIBRARY"],
                       provider="url",
                       max_bytes=int(os.getenv("TL_MAX_LIBRARY_MB", "700")) * 1024 * 1024)
    try:
        st = lib.stats()
    except Exception as exc:  # noqa: BLE001
        st = {"error": str(exc)[:200]}
    return jsonify({"status": "ok", "library": app.config["LIBRARY"], "storage": st})


def _disk_free_bytes(path: str) -> int:
    try:
        st = os.statvfs(path)
        return st.f_frsize * st.f_bavail
    except Exception:  # noqa: BLE001
        return -1


@app.post("/v1/download")
def download():
    data = request.get_json(silent=True) or {}
    url = (data.get("url") or "").strip()
    if not url.startswith(("http://", "https://")):
        return jsonify({"ok": False, "message": "a valid http(s) url is required"}), 400

    niche = (data.get("niche") or "manual").strip() or "manual"
    cookies_path = _write_cookies(data.get("cookies"))
    try:
        cap_mb = int(os.getenv("TL_MAX_LIBRARY_MB", "700"))
        lib = AudioLibrary(app.config["LIBRARY"],
                           provider="url",
                           cookies_file=cookies_path,
                           max_bytes=cap_mb * 1024 * 1024)

        # Refuse BEFORE downloading when the disk itself is nearly full. A failed
        # yt-dlp mid-write is what turns "disk full" into a crashed service; the
        # library cap alone cannot prevent it because one track can be large.
        free = _disk_free_bytes(app.config["LIBRARY"])
        min_free = int(float(os.getenv("TL_MIN_FREE_MB", "60")) * 1024 * 1024)
        if free >= 0 and free < min_free:
            try:
                lib._prune()          # try to make room first
            except Exception:         # noqa: BLE001
                pass
            free = _disk_free_bytes(app.config["LIBRARY"])
            if free < min_free:
                return jsonify({
                    "ok": False,
                    "message": (f"insufficient disk: {free // 1048576}MB free, "
                                f"{min_free // 1048576}MB required"),
                    "storage": lib.stats(),
                }), 507

        _download_slots.acquire()
        try:
            entry = lib.download_url(url, niche=niche,
                                     title=(data.get("title") or "").strip() or None,
                                     artist=(data.get("artist") or "").strip() or None)
        finally:
            _download_slots.release()
        entry.setdefault("storage", lib.stats())
        status = 200 if entry.get("ok") else 502
        return jsonify(entry), status
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)[:300]}), 500
    finally:
        if cookies_path:
            try:
                os.remove(cookies_path)
            except OSError:
                pass


@app.post("/v1/song")
def song():
    """Resolve a song NAME to audio (Instagram-first, then name search).

    Body: {"title": "...", "artist": "...", "niche": "reels",
           "instagram_url": "https://www.instagram.com/reel/.../",   # optional
           "cookies": [...]}                                          # optional
    This is the endpoint for "use the actual trending ones": feed it a row from
    /v1/trending and it comes back with a real audio file.
    """
    data = request.get_json(silent=True) or {}
    title = (data.get("title") or "").strip()
    if not title:
        return jsonify({"ok": False, "message": "title is required"}), 400

    niche = (data.get("niche") or "reels").strip() or "reels"
    ig_url = (data.get("instagram_url") or data.get("url") or "").strip() or None
    cookies_path = _write_cookies(data.get("cookies"))
    try:
        lib = AudioLibrary(app.config["LIBRARY"], provider="song",
                           cookies_file=cookies_path,
                           max_bytes=int(os.getenv("TL_MAX_LIBRARY_MB", "600")) * 1024 * 1024)
        free = _disk_free_bytes(app.config["LIBRARY"])
        min_free = int(float(os.getenv("TL_MIN_FREE_MB", "80")) * 1024 * 1024)
        if free >= 0 and free < min_free:
            return jsonify({"ok": False,
                            "message": f"insufficient disk: {free // 1048576}MB free",
                            "storage": lib.stats()}), 507

        _download_slots.acquire()
        try:
            entry = lib.download_song(title, (data.get("artist") or "").strip(),
                                      niche=niche, instagram_url=ig_url)
        finally:
            _download_slots.release()
        entry.setdefault("storage", lib.stats())
        return jsonify(entry), (200 if entry.get("ok") else 502)
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)[:300]}), 500
    finally:
        if cookies_path:
            try:
                os.remove(cookies_path)
            except OSError:
                pass


@app.get("/v1/library/<niche>")
def library(niche: str):
    manifest = os.path.join(app.config["LIBRARY"],
                            niche.strip().lower().replace(" ", "-"), "manifest.json")
    if not os.path.exists(manifest):
        return jsonify({"niche": niche, "entries": []})
    return jsonify({"niche": niche,
                    "entries": json.load(open(manifest))})


@app.get("/v1/file/<niche>/<path:filename>")
def serve_file(niche: str, filename: str):
    safe = os.path.basename(filename)  # no path traversal
    base = os.path.join(app.config["LIBRARY"], niche.strip().lower().replace(" ", "-"))
    target = os.path.abspath(os.path.join(base, safe))
    if not target.startswith(os.path.abspath(base)) or not os.path.isfile(target):
        abort(404)
    return send_file(target, as_attachment=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=int(os.getenv("PORT", "8000")))
    ap.add_argument("--host", default=os.getenv("HOST", "0.0.0.0"))
    ap.add_argument("--library", default=DEFAULT_LIBRARY)
    args = ap.parse_args()
    os.makedirs(args.library, exist_ok=True)
    app.config["LIBRARY"] = args.library
    app.run(host=args.host, port=args.port, threaded=True,
            debug=os.getenv("FLASK_DEBUG", "0") == "1")


if __name__ == "__main__":
    main()
